# Generated by Django 6.0.5 on 2026-06-24 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon')),
                ('password', models.CharField(max_length=255, verbose_name='Parol (hash)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Menejer',
                'verbose_name_plural': 'Menejerlar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('price_coins', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(unique=True)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('stage', models.IntegerField(default=1)),
                ('schedule', models.CharField(choices=[('odd', 'Du-Chor-Juma'), ('even', 'Se-Pay-Shan')], default='odd', max_length=10)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_excellence', models.BooleanField(default=False)),
                ('coin_balance', models.IntegerField(default=0, verbose_name='Coin balansi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_senior', models.BooleanField(default=False)),
                ('penalty_limit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('absent', 'Kelmadi'), ('late', 'Kech keldi')], default='absent', max_length=10)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='register_withvue.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='register_withvue.student')),
            ],
            options={
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price_coins', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Berildi'), ('rejected', 'Bekor qilindi')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='register_withvue.product')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='register_withvue.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('late', 'Kech kelish'), ('absent', 'Darsga kelmadi'), ('behavior', 'Xulq-atvor'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='register_withvue.student')),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_penalties', to='register_withvue.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='register_withvue.teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='register_withvue.teacher'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lesson_time', models.TimeField()),
                ('schedule', models.CharField(choices=[('odd', 'Du-Chor-Juma'), ('even', 'Se-Pay-Shan')], default='odd', max_length=10)),
                ('students', models.ManyToManyField(related_name='groups', to='register_withvue.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='register_withvue.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('exam_pass', "Imtihondan o'tdi"), ('homework_done', 'Vazifa qilingan'), ('homework_missed', 'Vazifa qilinmagan'), ('present', 'Darsga keldi'), ('late', 'Kech keldi'), ('absent', 'Darsga kelmadi'), ('manual', "Teacher tomonidan qo'lda"), ('purchase', 'Magazindan xarid'), ('purchase_cancel', 'Xarid bekor qilindi (qaytarildi)')], default='manual', max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions', to='register_withvue.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='register_withvue.student')),
                ('given_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions_given', to='register_withvue.teacher')),
            ],
            options={
                'verbose_name': 'Coin tranzaksiyasi',
                'verbose_name_plural': 'Coin tranzaksiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('stage', models.IntegerField()),
                ('amount_due', models.IntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='register_withvue.student')),
            ],
            options={
                'unique_together': {('student', 'month')},
            },
        ),
    ]
