# Generated by Django 6.0.5 on 2026-06-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCoinSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.IntegerField(default=5, verbose_name='Keldi')),
                ('late', models.IntegerField(default=2, verbose_name='Kech keldi')),
                ('absent', models.IntegerField(default=-10, verbose_name='Kelmadi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Davomat coin sozlamasi',
                'verbose_name_plural': 'Davomat coin sozlamalari',
            },
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='reason',
            field=models.CharField(choices=[('exam_pass', "Imtihondan o'tdi"), ('homework_done', 'Vazifa qilingan'), ('homework_partial', 'Vazifa chala qilingan'), ('homework_missed', 'Vazifa qilinmagan'), ('present', 'Darsga keldi'), ('late', 'Kech keldi'), ('absent', 'Darsga kelmadi'), ('manual', "Teacher tomonidan qo'lda"), ('purchase', 'Magazindan xarid'), ('purchase_cancel', 'Xarid bekor qilindi (qaytarildi)')], default='manual', max_length=20),
        ),
    ]
