# Generated by Django 6.0.5 on 2026-07-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0002_attendancecoinsettings_alter_cointransaction_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
