# Generated by Django 6.0.5 on 2026-06-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0002_teacher_penalty_limit_studentpenalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('price_coins', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('exam_pass', "Imtihondan o'tdi"), ('homework_done', 'Vazifa qilingan'), ('homework_missed', 'Vazifa qilinmagan'), ('present', 'Darsga keldi'), ('late', 'Kech keldi'), ('absent', 'Darsga kelmadi'), ('manual', "Teacher tomonidan qo'lda"), ('purchase', 'Magazindan xarid'), ('purchase_cancel', 'Xarid bekor qilindi (qaytarildi)')], default='manual', max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions', to='register_withvue.attendance')),
                ('given_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions_given', to='register_withvue.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='register_withvue.student')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price_coins', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Berildi'), ('rejected', 'Bekor qilindi')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='register_withvue.student')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='register_withvue.product')),
            ],
        ),
    ]
