# Generated by Django 6.0.6 on 2026-07-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0003_teacher_password_alter_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Xona'),
        ),
    ]
