# Generated by Django 6.0.5 on 2026-06-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0003_product_student_coins_cointransaction_order'),
        ('register_withvue', '0004_group'),
    ]

    operations = [
    ]
