# Generated by Django 6.0.6 on 2026-07-05 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0005_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('monthly_fee', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Davomat', 'verbose_name_plural': 'Davomatlar'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Guruh', 'verbose_name_plural': 'Guruhlar'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Dars', 'verbose_name_plural': 'Darslar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='stageprice',
            options={'verbose_name': 'Etap narxi', 'verbose_name_plural': 'Etap narxlari'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': "O'quvchi", 'verbose_name_plural': "O'quvchilar"},
        ),
        migrations.AlterModelOptions(
            name='studentpenalty',
            options={'verbose_name': "O'quvchi ja'zosi", 'verbose_name_plural': "O'quvchi ja'zolari"},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': "O'qituvchi", 'verbose_name_plural': "O'qituvchilar"},
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='register_withvue.course', verbose_name='Course'),
        ),
    ]
