# Generated by Django 6.0.6 on 2026-07-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0007_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
    ]
