# Generated by Django 6.0.6 on 2026-07-07 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_withvue', '0008_remove_student_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('amount', models.IntegerField(default=0, verbose_name='Summa')),
                ('category', models.CharField(choices=[('salary', 'Maosh'), ('utility', 'Kommunal'), ('equipment', 'Qurilmalar'), ('rent', 'Ijara'), ('marketing', 'Marketing'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Kategoriya')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
